
package INF;

import CODE.DBconect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class Drugs extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Drugs() {
        initComponents();
        conn = DBconect.connect();
        tableload();
    }
    
    public void tableload(){

            try {
                String sql = "SELECT Drug,Trade_Name,Formula,Supplying_Company,Available_Pharmacy FROM drugs";
                pst = conn.prepareStatement(sql);
                rs= pst.executeQuery();
                table3.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }

    public void tabledata() {
        int  r = table3.getSelectedRow();
        String Drug =table3.getValueAt(r, 0).toString();
        String Trade_Name = table3.getValueAt(r, 1).toString();
        String Formula = table3.getValueAt(r, 2).toString();
        String 	Supplying_Company = table3.getValueAt(r, 3).toString();
        String 	Available_Pharmacy = table3.getValueAt(r, 4).toString();
        
        txtDrug.setText(Drug);
        txttradeN.setText(Trade_Name );
        txtFormula.setText( Formula);
        txtOwnedCompany.setText	(Supplying_Company);
        txtTextOfContract.setText(Available_Pharmacy);
        
        
    }
    
    public void search(){
    
       String srch= txtSearchD.getText();
        try {
            String sql = " SELECT * FROM drugs WHERE Trade_Name LIKE '%"+srch+"%' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            table3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
    }
    
    public void update(){
        
        String Drug = txtDrug.getText();
        String TradeName = txttradeN.getText();
        String Formula = txtFormula.getText();
        String 	Supplying_Company = txtOwnedCompany.getText();
        String 	Available_Pharmacy = txtTextOfContract.getText();
        
        try {
            String sql = "UPDATE drugs SET Drug = '"+Drug+"',Formula = '"+Formula+"',	Supplying_Company=  '"+	Supplying_Company+"',	Available_Pharmacy='"+	Available_Pharmacy +"' WHERE Trade_Name = '"+TradeName+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Updated!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null," Not Updated!");
        }
    }
    
    public void clear(){
        txtSearchD.setText("");
        txtDrug.setText("");
        txttradeN.setText("");
        txtFormula.setText("");
        txtOwnedCompany.setText("");
        txtTextOfContract.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDrug = new javax.swing.JLabel();
        txtDrug = new javax.swing.JTextField();
        lbltradeN = new javax.swing.JLabel();
        txttradeN = new javax.swing.JTextField();
        lblFormula = new javax.swing.JLabel();
        txtFormula = new javax.swing.JTextField();
        lblOwnedCompany = new javax.swing.JLabel();
        txtOwnedCompany = new javax.swing.JTextField();
        lblTextOfContract = new javax.swing.JLabel();
        txtTextOfContract = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSearchD = new javax.swing.JLabel();
        txtSearchD = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCkear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        btnUpdate2 = new javax.swing.JButton();
        icon7 = new javax.swing.JLabel();
        txtFormula1 = new javax.swing.JTextField();
        lblFormula1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText(" DRUG DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 470, 40));

        lblDrug.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblDrug.setText("DRUG");
        getContentPane().add(lblDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 280, 20));

        txtDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugActionPerformed(evt);
            }
        });
        getContentPane().add(txtDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 280, 30));

        lbltradeN.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbltradeN.setText("TRADE NAME");
        getContentPane().add(lbltradeN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 280, 20));

        txttradeN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttradeNActionPerformed(evt);
            }
        });
        getContentPane().add(txttradeN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 280, 30));

        lblFormula.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblFormula.setText("FORMULA");
        getContentPane().add(lblFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 280, 20));

        txtFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 280, 30));

        lblOwnedCompany.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblOwnedCompany.setText("SUPPLYING COMPANY");
        getContentPane().add(lblOwnedCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 280, 20));

        txtOwnedCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnedCompanyActionPerformed(evt);
            }
        });
        getContentPane().add(txtOwnedCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 280, 30));

        lblTextOfContract.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTextOfContract.setText("AVAILABLE PHARMACY");
        getContentPane().add(lblTextOfContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 280, 20));

        txtTextOfContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTextOfContractActionPerformed(evt);
            }
        });
        getContentPane().add(txtTextOfContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("SEARCH A DRUG");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 360, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearchD.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblSearchD.setText("TRADE NAME");
        jPanel1.add(lblSearchD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 20));

        txtSearchD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDActionPerformed(evt);
            }
        });
        txtSearchD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchDKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearchD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 280, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 550, 60));

        btnDelete.setBackground(new java.awt.Color(255, 255, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 110, 30));

        btnsave.setBackground(new java.awt.Color(255, 255, 204));
        btnsave.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 110, 30));

        btnExit.setBackground(new java.awt.Color(255, 255, 204));
        btnExit.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, 120, 30));

        btnBack.setBackground(new java.awt.Color(255, 255, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 110, 30));

        btnCkear.setBackground(new java.awt.Color(255, 255, 204));
        btnCkear.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnCkear.setText("CLEAR");
        btnCkear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCkearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCkear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 110, 30));

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        table3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table3KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 520, -1));

        btnUpdate2.setBackground(new java.awt.Color(255, 255, 204));
        btnUpdate2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnUpdate2.setText("UPDATE");
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 110, 30));

        icon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INF/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(icon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 600));

        txtFormula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormula1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtFormula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 280, 30));

        lblFormula1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblFormula1.setText("FORMULA");
        getContentPane().add(lblFormula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 280, 20));

        setSize(new java.awt.Dimension(899, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int check = JOptionPane.showConfirmDialog(null, "DO YOU WANT TO DELETE");
        
        if (check==0){
            String TradeName = txttradeN.getText();
            try {
                String sql = "DELETE FROM drugs WHERE Trade_Name = '"+TradeName+"' ";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null," DELETED!");   
            } catch (Exception e) {
             JOptionPane.showMessageDialog(null,"NOT DELETE!");   
            }
        }
         tableload();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        
        String Drug;
        String TradeName;
        String Formula;
        String 	Supplying_Company;
        String 	Available_Pharmacy;
        
        Drug = txtDrug.getText();
        TradeName = txttradeN.getText();
        Formula = txtFormula.getText();
        	Supplying_Company = txtOwnedCompany.getText();
        Available_Pharmacy = txtTextOfContract.getText();
        
        try {
            String sql = "INSERT INTO drugs (Drug,Trade_Name,Formula,	Supplying_Company,Available_Pharmacy) VALUES ('"+Drug+"' , '"+TradeName+"' , '"+Formula+"' , '"+	Supplying_Company+"' , '"+	Available_Pharmacy+"' )";
            pst = conn.prepareStatement(sql); 
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        tableload();
                
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCkearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCkearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnCkearActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        // TODO add your handling code here:
        update();
        tableload();
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
        // TODO add your handling code here:
        tabledata();
    }//GEN-LAST:event_table3MouseClicked

    private void table3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table3KeyReleased
        // TODO add your handling code here:
        tabledata();
        
    }//GEN-LAST:event_table3KeyReleased

    private void txtSearchDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchDKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_txtSearchDKeyReleased

    private void txtDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugActionPerformed

    private void txttradeNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttradeNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttradeNActionPerformed

    private void txtFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormulaActionPerformed

    private void txtOwnedCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnedCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnedCompanyActionPerformed

    private void txtTextOfContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTextOfContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTextOfContractActionPerformed

    private void txtFormula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormula1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drugs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCkear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel icon7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDrug;
    private javax.swing.JLabel lblFormula;
    private javax.swing.JLabel lblFormula1;
    private javax.swing.JLabel lblOwnedCompany;
    private javax.swing.JLabel lblSearchD;
    private javax.swing.JLabel lblTextOfContract;
    private javax.swing.JLabel lbltradeN;
    private javax.swing.JTable table3;
    private javax.swing.JTextField txtDrug;
    private javax.swing.JTextField txtFormula;
    private javax.swing.JTextField txtFormula1;
    private javax.swing.JTextField txtOwnedCompany;
    private javax.swing.JTextField txtSearchD;
    private javax.swing.JTextField txtTextOfContract;
    private javax.swing.JTextField txttradeN;
    // End of variables declaration//GEN-END:variables
}
