
package INF;

import CODE.DBconect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class RegisterCompaniiesOrSearch extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;


    
    
    public RegisterCompaniiesOrSearch() {
        initComponents();
        conn = DBconect.connect();
        tableload();
    }
    
    public void tableload(){

            try {
                String sql = "SELECT Company_Name,Include_Pharmacies,Address,Phone_Number,Text_of_Contract,Start_date,End_date FROM  pharmaceutical_companies";
                pst = conn.prepareStatement(sql);
                rs= pst.executeQuery();
                tbl1.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }
    
     public void tabledata() {
        int  r = tbl1.getSelectedRow();
        String Company_Name =tbl1.getValueAt(r, 0).toString();
        String Include_Pharmacies = tbl1.getValueAt(r, 1).toString();
        String Address = tbl1.getValueAt(r, 2).toString();
        String Phone_Number = tbl1.getValueAt(r, 3).toString();
        String Text_of_Contract = tbl1.getValueAt(r, 4).toString();
        String Start_date = tbl1.getValueAt(r, 5).toString();
        String End_date = tbl1.getValueAt(r, 6).toString();
        
        txtCNName.setText(Company_Name);
        txtIPhm.setText(Include_Pharmacies );
        txtAddress.setText( Address);
        txtPNumber.setText(Phone_Number);
        txtTOContract.setText(Text_of_Contract);
        txtSDate.setText(Start_date);
        TXTEDATE.setText(End_date);
        
       
        
        
    }
     
    
     
     public void search(){
    
       String srch= txtlSearchCN.getText();
        try {
            String sql = " SELECT * FROM pharmaceutical_companies WHERE Company_Name LIKE '%"+srch+"%' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tbl1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
    }
     
     
    public void update(){
    
        String companyName = txtCNName.getText();
        String includePharmacies = txtIPhm.getText();
        String  address = txtAddress.getText();     
        String  phoneNumber = txtPNumber.getText();  
        String Contract = txtTOContract.getText();
        String startDate = txtSDate.getText();
        String endtDate = TXTEDATE.getText();
        
        try {
            String sql = "UPDATE pharmaceutical_companies SET Include_Pharmacies = '"+includePharmacies+"',Address = '"+address+"' ,Phone_Number = '"+phoneNumber+"',Text_of_Contract = '"+Contract+"',Start_date = '"+startDate+"',End_date ='"+endtDate+"' WHERE  Company_Name = '"+companyName+"' ";
            pst = conn.prepareStatement(sql); 
            pst.execute();
            JOptionPane.showMessageDialog(null,"Updated!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null," Not Updated!");
        }
    }
    
    
    public void clear(){
         txtlSearchCN.setText("");
         txtCNName.setText("");
         txtIPhm.setText("");
         txtAddress.setText("");
         txtPNumber.setText("");
         txtTOContract.setText("");
         txtSDate.setText("");
         TXTEDATE.setText("");
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblIPhm = new javax.swing.JLabel();
        txtPNumber = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPNumber = new javax.swing.JLabel();
        txtTOContract = new javax.swing.JTextField();
        lblTOContract = new javax.swing.JLabel();
        txtSDate = new javax.swing.JTextField();
        lblSDate = new javax.swing.JLabel();
        txtCNName = new javax.swing.JTextField();
        lblEDate = new javax.swing.JLabel();
        TXTEDATE = new javax.swing.JTextField();
        txtIPhm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSearchCN = new javax.swing.JLabel();
        txtlSearchCN = new javax.swing.JTextField();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        lblCName = new javax.swing.JLabel();
        btnSave1 = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        icon5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("SEARCH A COMPANY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 330, 30));

        lblIPhm.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblIPhm.setText("INCLUDE PHARMACIES");
        getContentPane().add(lblIPhm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 300, 20));

        txtPNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtPNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 320, 30));

        lblAddress.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblAddress.setText("ADDRESS");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, 20));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 320, 30));

        lblPNumber.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblPNumber.setText("PHONE NUMBER");
        getContentPane().add(lblPNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 300, 20));

        txtTOContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTOContractActionPerformed(evt);
            }
        });
        getContentPane().add(txtTOContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 320, 30));

        lblTOContract.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblTOContract.setText("TEXT OF CONTRACT");
        getContentPane().add(lblTOContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 300, 20));

        txtSDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtSDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 320, 30));

        lblSDate.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblSDate.setText("START DATE");
        getContentPane().add(lblSDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 300, 20));
        getContentPane().add(txtCNName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 320, 30));

        lblEDate.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblEDate.setText("END DATE");
        getContentPane().add(lblEDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 300, 20));
        getContentPane().add(TXTEDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 320, 30));

        txtIPhm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPhmActionPerformed(evt);
            }
        });
        getContentPane().add(txtIPhm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 320, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("REGISTER A NEW COMPANY");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SEARCH"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearchCN.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblSearchCN.setText("Company Name");
        jPanel1.add(lblSearchCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 20));

        txtlSearchCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlSearchCNActionPerformed(evt);
            }
        });
        txtlSearchCN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlSearchCNKeyReleased(evt);
            }
        });
        jPanel1.add(txtlSearchCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 320, -1));

        btnUpdate1.setBackground(new java.awt.Color(255, 255, 204));
        btnUpdate1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnUpdate1.setText("UPDATE");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 120, 30));

        btnDelete1.setBackground(new java.awt.Color(255, 255, 204));
        btnDelete1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnDelete1.setText("DELETE");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 820, 70));

        lblCName.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblCName.setText("Company Name");
        getContentPane().add(lblCName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 300, 20));

        btnSave1.setBackground(new java.awt.Color(255, 255, 204));
        btnSave1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnSave1.setText("SAVE");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 100, 30));

        btnClear2.setBackground(new java.awt.Color(255, 255, 204));
        btnClear2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnClear2.setText("CLEAR");
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 100, 30));

        btnBack.setBackground(new java.awt.Color(255, 255, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, 100, 50));

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        tbl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 860, 320));

        icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INF/maxresdefault.jpg"))); // NOI18N
        icon5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                icon5KeyReleased(evt);
            }
        });
        getContentPane().add(icon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 630));

        setSize(new java.awt.Dimension(1279, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIPhmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPhmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPhmActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtPNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPNumberActionPerformed

    private void txtTOContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTOContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTOContractActionPerformed

    private void txtSDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDateActionPerformed

    private void txtlSearchCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlSearchCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlSearchCNActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        int check = JOptionPane.showConfirmDialog(null, "DO YOU WANT TO DELETE");
        
        if (check==0){
            String companyName = txtCNName.getText();
            try {
                String sql = "DELETE FROM pharmaceutical_companies WHERE Company_Name = '"+companyName+"' ";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null," DELETED!");   
            } catch (Exception e) {
             JOptionPane.showMessageDialog(null,"NOT DELETE!");   
            }
        }
         tableload();
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        update();
        tableload();
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        
       
        String companyName;
        String includePharmacies;
        String address;
        String phoneNumber;
        String Contract;
        String startDate;
        String endtDate;
        
        
       
        companyName = txtCNName.getText();
        includePharmacies = txtIPhm.getText();
        address = txtAddress.getText();
        phoneNumber = txtPNumber.getText();
        Contract = txtTOContract.getText();
        startDate = txtSDate.getText();
        endtDate = TXTEDATE.getText();
        
        try {
            String sql = "INSERT INTO pharmaceutical_companies(Company_Name,Include_Pharmacies,Address,Phone_Number,Text_of_Contract,Start_date,End_date) VALUES ('"+companyName+"' , '"+includePharmacies+"' , '"+address+"' , '"+phoneNumber+"' , '"+Contract+"', '"+startDate+"', '"+endtDate+"' )";
            pst = conn.prepareStatement(sql); 
            pst.execute();
            JOptionPane.showMessageDialog(null," Registered!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tableload();
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        // TODO add your handling code here:
        tabledata();
    }//GEN-LAST:event_tbl1MouseClicked

    private void tbl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl1KeyReleased
        // TODO add your handling code here:
        tabledata();
    }//GEN-LAST:event_tbl1KeyReleased

    private void icon5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icon5KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_icon5KeyReleased

    private void txtlSearchCNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlSearchCNKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_txtlSearchCNKeyReleased

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        clear();
    }//GEN-LAST:event_btnClear2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterCompaniiesOrSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterCompaniiesOrSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterCompaniiesOrSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterCompaniiesOrSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterCompaniiesOrSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTEDATE;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblEDate;
    private javax.swing.JLabel lblIPhm;
    private javax.swing.JLabel lblPNumber;
    private javax.swing.JLabel lblSDate;
    private javax.swing.JLabel lblSearchCN;
    private javax.swing.JLabel lblTOContract;
    private javax.swing.JTable tbl1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCNName;
    private javax.swing.JTextField txtIPhm;
    private javax.swing.JTextField txtPNumber;
    private javax.swing.JTextField txtSDate;
    private javax.swing.JTextField txtTOContract;
    private javax.swing.JTextField txtlSearchCN;
    // End of variables declaration//GEN-END:variables
}
