
package INF;

import CODE.DBconect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class RegisterPharmacyOrSearch extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public RegisterPharmacyOrSearch() {
        initComponents();
        conn = DBconect.connect();
        tableload();
    }
    
    public void tableload(){

            try {
                String sql = "SELECT Pharmacy_Name,Pharmacy_Code,Address,Phone_Number FROM pharmacies";
                pst = conn.prepareStatement(sql);
                rs= pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }
    
    public void tabledata() {
        int  r = jTable1.getSelectedRow();
        String Pharmacy_Name =jTable1.getValueAt(r, 0).toString();
        String Pharmacy_Code = jTable1.getValueAt(r, 1).toString();
        String Address = jTable1.getValueAt(r, 2).toString();
        String Phone_Number = jTable1.getValueAt(r, 3).toString();
        
        
        txtPname.setText(Pharmacy_Name);
        txtPcode.setText(Pharmacy_Code );
        txtAddress.setText( Address);
        txtPNum.setText(Phone_Number);
        
        
        
    }
    
     public void search(){
    
       String srch= txtlSearchP.getText();
        try {
            String sql = " SELECT * FROM pharmacies WHERE Pharmacy_Code LIKE '%"+srch+"%' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
    }
     
    
     public void update(){
     
        String PhName= txtPname.getText();
        String PhCode= txtPcode.getText();
        String address= txtAddress.getText();
        String phoneNumber= txtPNum.getText();
        
         try {
             String sql = "UPDATE  pharmacies SET Pharmacy_Name = '"+PhName+"' ,  Address ='"+address+"'  , Phone_Number = '"+phoneNumber+"' WHERE Pharmacy_Code = '"+PhCode+"' ";
             pst = conn.prepareStatement(sql); 
            pst.execute();
            JOptionPane.showMessageDialog(null, "UPDATED");
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "NOT UPDATED");
         }
         
     }
     
     public void clear(){
         txtlSearchP.setText("");
         txtPname.setText("");
         txtPcode.setText("");
         txtAddress.setText("");
         txtPNum.setText("");
         
     }
     
        
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPname = new javax.swing.JLabel();
        txtPname = new javax.swing.JTextField();
        kblPcode = new javax.swing.JLabel();
        txtPcode = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPNum = new javax.swing.JLabel();
        txtPNum = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtlSearchP = new javax.swing.JTextField();
        lblSearchP = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        icon6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("SEARCH A PHARMACY ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 320, 30));

        lblPname.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblPname.setText("PHARMACY NAME");
        getContentPane().add(lblPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 20));
        getContentPane().add(txtPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 30));

        kblPcode.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        kblPcode.setText("PHARMACY CODE");
        getContentPane().add(kblPcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 20));
        getContentPane().add(txtPcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, 30));

        lblAddress.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblAddress.setText("ADDRESS");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 280, 20));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 30));

        lblPNum.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblPNum.setText("PHONE NUMBER");
        getContentPane().add(lblPNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 280, 20));
        getContentPane().add(txtPNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 280, 30));

        btnBack.setBackground(new java.awt.Color(255, 255, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 110, 40));

        btnClear.setBackground(new java.awt.Color(255, 255, 204));
        btnClear.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("REGISTER A NEW PHARMACY ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtlSearchP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlSearchPKeyReleased(evt);
            }
        });

        lblSearchP.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblSearchP.setText("PHARMACY CODE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchP, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(txtlSearchP, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlSearchP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 630, 70));

        btnSave.setBackground(new java.awt.Color(255, 255, 204));
        btnSave.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 110, 30));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 204));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 110, 30));

        btnDelete.setBackground(new java.awt.Color(255, 255, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 110, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 700, 420));

        icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INF/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(icon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 570));

        setSize(new java.awt.Dimension(1073, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String PhName;
        String PhCode;
        String address;
        String phoneNumber;
        
        
        PhName = txtPname.getText();
        PhCode = txtPcode.getText();
        address = txtAddress.getText();
        phoneNumber= txtPNum.getText();
        
        try {
            String sql = "INSERT INTO pharmacies (Pharmacy_Name,Pharmacy_Code,Address,Phone_Number) VALUES ('"+PhName+"' , '"+PhCode+"' , '"+address+"' , '"+phoneNumber+"'  )";
            pst = conn.prepareStatement(sql); 
            pst.execute();
            JOptionPane.showMessageDialog(null, "REGISTERED");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tableload();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        update();
        tableload();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int check = JOptionPane.showConfirmDialog(null, "DO YOU WANT TO DELETE");
        
        if (check==0){
            String PhCode = txtPcode.getText();
            try {
                String sql = "DELETE FROM pharmacies WHERE Pharmacy_Code = '"+PhCode+"' ";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null," DELETED!");   
            } catch (Exception e) {
             JOptionPane.showMessageDialog(null,"NOT DELETE!");   
            }
        }
         tableload();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         tabledata();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
         tabledata();
    }//GEN-LAST:event_jTable1KeyReleased

    private void txtlSearchPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlSearchPKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_txtlSearchPKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPharmacyOrSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPharmacyOrSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPharmacyOrSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPharmacyOrSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPharmacyOrSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel icon6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kblPcode;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblPNum;
    private javax.swing.JLabel lblPname;
    private javax.swing.JLabel lblSearchP;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtPNum;
    private javax.swing.JTextField txtPcode;
    private javax.swing.JTextField txtPname;
    private javax.swing.JTextField txtlSearchP;
    // End of variables declaration//GEN-END:variables
}
